name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: make install

      - name: Run Mongo
        run: |
          docker run -d --rm --name mongo -p 27017:27017 mongo
          docker ps -a

      - name: Test
        run: yarn test --coverage
        env:
          CI: true
        
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}