name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: make install

      - name: Test
        run: yarn test --coverage
        env:
          CI: true
        
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}